### ISSUE TITLE
When i click "edit" on the master channel button, nothing happens aside from the trigger blinking

### ISSUE THREAD

**Issue by hems** [gibber-cc/gibberwocky.live#1]
OSX 10.12
Max 7.3.1
Ableton 9.7

When i click "open patch" it shows a bunch of errors on the console :(

<img width="768" alt="screen shot 2017-06-23 at 05 21 29" src="https://user-images.githubusercontent.com/27327/27466596-d809c51c-57d3-11e7-8200-0a3db7c4fc2f.png">

**Comment by charlieroberts** [comment]
Hi,

Unfortunately we're still working on some workarounds for people who don't have full Max for Live licenses, as the Gen integration requires it. In the meantime you might be able to use http://gibber.cc/live to play around with gibberwocky, but the Gen-based modulations won't work :(

Let me know if that URL works for you! - Charlie

**Comment by hems** [comment]
@charlieroberts thanks for your quick reply!

If i do the monthly subscription on Max will it be enough?

https://cycling74.com/shop

**Comment by hems** [comment]
@charlieroberts regarding the /live URL it's yielding 404

<img width="331" alt="screen shot 2017-06-26 at 02 48 57" src="https://user-images.githubusercontent.com/27327/27521958-0d176db6-5a1a-11e7-807c-cb15a3ed307f.png">

**Comment by charlieroberts** [comment]
Sorry! That URL should have been http://gibberwocky.cc/live

I'm assuming the mostly licensing of Max should be fine.

**Comment by softpunch** [comment]
Hey--

Just to clarify, 
does that mean the device currently only works with a full MAX license?
Or it just requires a full Max 4 Live license?

I have a full M4L license, but I don't have a standalone Max 7 license.
M4L allows _use_ of Gen patches, but it doesn't allow editing or authoring of them.

I haven't been able to get Gibberwocky to work properly inside Live, 
and I'm not sure if that's expected or not with an M4L license.

When I click "edit" in the main Gibberwocky device in Live, 
a finder instance opens and nothing happens.
(It's not actually a file->open dialog, it's just a Finder instance.)

If I try to edit the device, I get two errors:
1. "in: codebox inlet 0 ignored
codebox: patchcord inlet out of range: deleting patchcord"
I'm not sure what this one is about.

2. "Gen not authorized on this install"
That one is expected.

I have the most recent versions of Max (via M4L) and Ableton, 
and I'm running El Capitan.

**Comment by softpunch** [comment]
Clarification:

The "Edit" button does nothing*
and if I double-click on "p edit", this is the result:

![screen shot 2017-07-12 at 3 49 25 pm](https://user-images.githubusercontent.com/19437970/28137115-1c76103e-671a-11e7-80ce-b68f3c09475a.png)

*(Not sure why it was opening a Finder window before.)

I had the same result on both my macbook and my mac pro.

**Comment by softpunch** [comment]
I'm not if this is relevant or not, 
but when I open the device with the Max editor button, 
it is **not** frozen.

**Comment by grrrwaaa** [comment]
Hi,

Without a full Max license, the signal based modulations (LFOs etc.) won’t work unfortunately, as this depends on using gen~ behind the scenes. But the rest of it should work. 

Clicking edit might open a Finder window if you have Finder defined as the default app for .html files. Clicking the edit button basically asks the OS to open the editor .html page in whatever the default app is, which would normally be one of your browsers. But using http://gibberwocky.cc/live should work.

>  "in: codebox inlet 0 ignored
> codebox: patchcord inlet out of range: deleting patchcord”
- this error can be ignored, it’s entirely harmless. 

Whoops about the devices not being frozen; just pushed the fix. Not sure that it matters much.

Graham

**Comment by magwa101** [comment]
I would really like to use jabberwocky for modulation. However, I think I'm in "no mans land".
I'm trying to use jabberwocky with:
Ableton 10 Suite (M4L bundled as Max 8)
High Sierra 10.13.3
Max 8

There is no Max 8 available yet from cycling74. Standalone Max 8 "available Q2".

To get full capabilities do I have to go back to Ableton 9 and buy Max 7?

**Comment by charlieroberts** [comment]
Hello,

In the most recent version, if a full Max license is not detected the fallback is to use genish.js, a JS library that approximates Gen, and then send the results to Ableton over the socket (instead of compiling Gen graphs in the plugin). This should work fine. 

Here's an example: https://youtu.be/dieGOIrp2L4

This was done running Live 10 Suite (beta). There's some plugin modulations happening about halfway through or so.

This isn't quite as cool as sending Gen code over the socket to be compiled / connected (those run at much higher sampling rates), but it will do the job for many situations. Let me know how it goes! I'm closing this issue but feel free to continue the conversation in it. - Charlie

**Comment by charlieroberts** [comment]
PS - I just published a new release with these changes: https://github.com/gibber-cc/gibberwocky.live/releases/tag/v1.2

You can also use them at http://gibberwocky.cc/live
