### ISSUE TITLE
recording midi and automation

### ISSUE THREAD

**Issue by magwa101** [gibber-cc/gibberwocky.live#11]
This is an amazing program for sketching ideas and experimenting quickly.

If I could record everything, midi, automation, etc. I could go back and edit for rock solid timing on a final mix.

It may not be a goal, but it's a usage I was thinking of.

I think it's an amazing piece of work and integrating with Live is great to leverage all the instruments it provides.

**Comment by magwa101** [comment]
Actually, I got it working by using "Midi From" on another track. Not sure what is different but looks to be working great!

**Comment by charlieroberts** [comment]
Hmmm... that might be a (purely unintended) benefit to using genish.js for modulation instead of Gen. I don't think there's anyway to capture the Gen modulations. Nice!
