### ISSUE TITLE
"Gen not authorized on this install" despite Max8 and ableton 10 suite licenses

### ISSUE THREAD

**Issue by JTriggerFish** [gibber-cc/gibberwocky.live#18]
I'm getting this error from the websocket feed even though I have the latest version of Max 8 and ableton suite installed. I have no problem using gen in live.
I couldn't figure out where this is thrown on the Max side ( I'm not very good at Max ) , if you could point me in the direction I may be able to find more details on the issue ?

**Comment by grrrwaaa** [comment]
Does it work if you install Max 7 instead? Max 8 was only recently released and I think I heard that the corresponding version of Ableton Live/Max for Live hasn't been released yet. (This is only guesswork, I'm not 100% sure how the licensing works across Max and Live versions.)

**Comment by JTriggerFish** [comment]
Unfortunately I'm not able to test as I don't have max 7 installed and I can't find the binaries on cycling74's website.
I think there was a period of time before Max8 was released where Max4live was using a preview version of Max8 where Gen was disabled, however as far as I'm aware this is not the case anymore; certainly **gen~** seems to work fine inside Max4live for me.
Would you know where that message is generated inside the Max4live side of gibberwocky so I can try and debug it ?

**Comment by charlieroberts** [comment]
@JTriggerFish for older versions see: https://cycling74.com/downloads/older

I think the version at http://gibberwocky.cc/beta/ should work even if gen~ isn't licensed, by using genish.js and sending messages over the web socket instead of creating gen~ graphs. Is that not the case? Obviously it would be better if licensing was working correctly...

**Comment by JTriggerFish** [comment]
Cool, thank you. Yes I think even the main repo uses genish in that case ( not 100% sure it works but looks like it should ).
But yes it would be good if I could get gen to work, I will try with max7 installed.

**Comment by grrrwaaa** [comment]
Quick reply from public transport... Max 7 can be downloaded here:
https://cycling74.com/downloads/older

**Comment by JTriggerFish** [comment]
Thx both !
Installing Max 7 didn't help, however after quite a few incantations - checking licenses in Max and in Live, editing gen patches in Max4live, opening max and live at the same time, the error eventually went away !?

There must be something funky on their side. However for now I'm happy it's working, hope it stays this way !
