### ISSUE TITLE
Unstable time when coding directly in Max

### ISSUE THREAD

**Issue by ErnestoAzuero** [gibber-cc/gibberwocky.live#2]
Hi, 
I'm new in live coding and I'm having some problems

I have a Max patch where I only have one bass sound playing on a sequence of two notes, velocity : one stronger than the other. In fact I'm using the same configuration as the examples you have on the demos. Although I changed some things, ['Bass'] instead of ['bass'] for example (just for the learning experience (^_^)), and I added a stereo delay on the drums but they are bypassed, not the drums nor the delay are on. That is it, no more processing is running. 

When I make the code run, what must be a simple periodic rhythm (a 1/4 or 1/8 note continuum), changes in weird ways and is very unstable and sometimes some notes just don't sound, so there is no regularity. It is a very simple computation really. (it is cool that is very random, but not what I expect to do at the moment).

I watched the videos posted on C'74 and I saw that the code ran smoothly and without this kind of computation and clock problems/bugs. So, I do not know if the problem is that Gibber is more stable under Ableton live or if, on Max, I have to run some other clock/code to optimize it. Or if I have to make some bigger DSP configuration  #changes.

I would be very thankful if someone could help me on this.

Best 
Ernesto

**Comment by grrrwaaa** [comment]
Hi Ernesto,

The timing should be pretty tight, so long as things are set up nicely. What browser/OS are you using?

Is Max’s Audio Settings set with “Scheduler in Overdrive” and "Audio Interrupt” enabled? (Look in Options menu, Audio Status). The audio timing of Max in general can be sloppier without these enabled. 

Other than that, if you can send a simple patcher plus some simple Gibberwocky code sample that will cause the poor timing, I can take a look.

Thanks,

Graham

**Comment by ErnestoAzuero** [comment]
Hi Graham

Ok. I had it configured without the SCHinOD or Audio Interrupt because for my usual patches and needs I do not need them to be on, so now I'll have to program configs by project.
I'm going to use this config and i'll tell you how it went.

Thank you 
:)

**Comment by charlieroberts** [comment]
Checking in... how'd it go?

**Comment by ErnestoAzuero** [comment]
It works like a charm Charlie! thanx!!!
;)
